package com.dbquality.core;

import com.dbquality.collector.SQLContext;
import com.dbquality.collector.SQLRecord;
import com.dbquality.config.QualityConfig;

import com.dbquality.constant.Constant;
import com.dbquality.util.SQLFilter;
import java.sql.*;
import java.time.Instant;
import java.util.Collections;

/**
 * Wrap Statement gốc để intercept việc thực thi SQL.
 * Tương tự QualityPreparedStatement nhưng dành cho Statement thường (không có parameters).
 */
public class QualityStatement implements Statement {

  private final Statement original;
  private final SQLContext sqlContext;
  private final QualityConfig config;

  public QualityStatement(Statement original, SQLContext sqlContext, QualityConfig config) {
    this.original = original;
    this.sqlContext = sqlContext;
    this.config = config;
  }

  // ── Intercept execute methods ─────────────────────────────────────

  @Override
  public ResultSet executeQuery(String sql) throws SQLException {
    long start = System.currentTimeMillis();
    try {
      ResultSet result = original.executeQuery(sql);
      record(sql, System.currentTimeMillis() - start, true, null);
      return result;
    } catch (SQLException e) {
      record(sql, System.currentTimeMillis() - start, false, e.getMessage());
      throw e;
    }
  }

  @Override
  public int executeUpdate(String sql) throws SQLException {
    long start = System.currentTimeMillis();
    try {
      int result = original.executeUpdate(sql);
      record(sql, System.currentTimeMillis() - start, true, null);
      return result;
    } catch (SQLException e) {
      record(sql, System.currentTimeMillis() - start, false, e.getMessage());
      throw e;
    }
  }

  @Override
  public boolean execute(String sql) throws SQLException {
    long start = System.currentTimeMillis();
    try {
      boolean result = original.execute(sql);
      record(sql, System.currentTimeMillis() - start, true, null);
      return result;
    } catch (SQLException e) {
      record(sql, System.currentTimeMillis() - start, false, e.getMessage());
      throw e;
    }
  }

  @Override
  public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    long start = System.currentTimeMillis();
    try {
      int result = original.executeUpdate(sql, autoGeneratedKeys);
      record(sql, System.currentTimeMillis() - start, true, null);
      return result;
    } catch (SQLException e) {
      record(sql, System.currentTimeMillis() - start, false, e.getMessage());
      throw e;
    }
  }

  @Override
  public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
    long start = System.currentTimeMillis();
    try {
      int result = original.executeUpdate(sql, columnIndexes);
      record(sql, System.currentTimeMillis() - start, true, null);
      return result;
    } catch (SQLException e) {
      record(sql, System.currentTimeMillis() - start, false, e.getMessage());
      throw e;
    }
  }

  @Override
  public int executeUpdate(String sql, String[] columnNames) throws SQLException {
    long start = System.currentTimeMillis();
    try {
      int result = original.executeUpdate(sql, columnNames);
      record(sql, System.currentTimeMillis() - start, true, null);
      return result;
    } catch (SQLException e) {
      record(sql, System.currentTimeMillis() - start, false, e.getMessage());
      throw e;
    }
  }

  @Override
  public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
    long start = System.currentTimeMillis();
    try {
      boolean result = original.execute(sql, autoGeneratedKeys);
      record(sql, System.currentTimeMillis() - start, true, null);
      return result;
    } catch (SQLException e) {
      record(sql, System.currentTimeMillis() - start, false, e.getMessage());
      throw e;
    }
  }

  @Override
  public boolean execute(String sql, int[] columnIndexes) throws SQLException {
    long start = System.currentTimeMillis();
    try {
      boolean result = original.execute(sql, columnIndexes);
      record(sql, System.currentTimeMillis() - start, true, null);
      return result;
    } catch (SQLException e) {
      record(sql, System.currentTimeMillis() - start, false, e.getMessage());
      throw e;
    }
  }

  @Override
  public boolean execute(String sql, String[] columnNames) throws SQLException {
    long start = System.currentTimeMillis();
    try {
      boolean result = original.execute(sql, columnNames);
      record(sql, System.currentTimeMillis() - start, true, null);
      return result;
    } catch (SQLException e) {
      record(sql, System.currentTimeMillis() - start, false, e.getMessage());
      throw e;
    }
  }

  // ── Record SQL execution ──────────────────────────────────────────

  private void record(String sql, long executionTime, boolean success, String errorMessage) {
    if (!SQLFilter.isApplicationSQL(sql)) return;
    sqlContext.add(SQLRecord.builder()
        .sql(sql)
        .parameters(Collections.emptyMap())
        .executionTime(executionTime)
        .timestamp(Instant.now())
        .calledFrom(captureCalledFrom())
        .success(success)
        .errorMessage(errorMessage)
        .build());
  }

  private String captureCalledFrom() {
    StackTraceElement[] stack = Thread.currentThread().getStackTrace();
    for (StackTraceElement frame : stack) {
      String className = frame.getClassName();
      boolean isInternal = Constant.INTERNAL_PREFIXES.stream()
          .anyMatch(className::startsWith);
      if (!isInternal) {
        return className + ":" + frame.getLineNumber()
            + " -> " + frame.getMethodName() + "()";
      }
    }
    return "unknown";
  }

  // ── Delegate các method còn lại về original ───────────────────────

  @Override public void close() throws SQLException { original.close(); }
  @Override public int getMaxFieldSize() throws SQLException { return original.getMaxFieldSize(); }
  @Override public void setMaxFieldSize(int max) throws SQLException { original.setMaxFieldSize(max); }
  @Override public int getMaxRows() throws SQLException { return original.getMaxRows(); }
  @Override public void setMaxRows(int max) throws SQLException { original.setMaxRows(max); }
  @Override public void setEscapeProcessing(boolean enable) throws SQLException { original.setEscapeProcessing(enable); }
  @Override public int getQueryTimeout() throws SQLException { return original.getQueryTimeout(); }
  @Override public void setQueryTimeout(int seconds) throws SQLException { original.setQueryTimeout(seconds); }
  @Override public void cancel() throws SQLException { original.cancel(); }
  @Override public SQLWarning getWarnings() throws SQLException { return original.getWarnings(); }
  @Override public void clearWarnings() throws SQLException { original.clearWarnings(); }
  @Override public void setCursorName(String name) throws SQLException { original.setCursorName(name); }
  @Override public ResultSet getResultSet() throws SQLException { return original.getResultSet(); }
  @Override public int getUpdateCount() throws SQLException { return original.getUpdateCount(); }
  @Override public boolean getMoreResults() throws SQLException { return original.getMoreResults(); }
  @Override public void setFetchDirection(int direction) throws SQLException { original.setFetchDirection(direction); }
  @Override public int getFetchDirection() throws SQLException { return original.getFetchDirection(); }
  @Override public void setFetchSize(int rows) throws SQLException { original.setFetchSize(rows); }
  @Override public int getFetchSize() throws SQLException { return original.getFetchSize(); }
  @Override public int getResultSetConcurrency() throws SQLException { return original.getResultSetConcurrency(); }
  @Override public int getResultSetType() throws SQLException { return original.getResultSetType(); }
  @Override public void addBatch(String sql) throws SQLException { original.addBatch(sql); }
  @Override public void clearBatch() throws SQLException { original.clearBatch(); }
  @Override public int[] executeBatch() throws SQLException { return original.executeBatch(); }
  @Override public Connection getConnection() throws SQLException { return original.getConnection(); }
  @Override public boolean getMoreResults(int current) throws SQLException { return original.getMoreResults(current); }
  @Override public ResultSet getGeneratedKeys() throws SQLException { return original.getGeneratedKeys(); }
  @Override public int getResultSetHoldability() throws SQLException { return original.getResultSetHoldability(); }
  @Override public boolean isClosed() throws SQLException { return original.isClosed(); }
  @Override public void setPoolable(boolean poolable) throws SQLException { original.setPoolable(poolable); }
  @Override public boolean isPoolable() throws SQLException { return original.isPoolable(); }
  @Override public void closeOnCompletion() throws SQLException { original.closeOnCompletion(); }
  @Override public boolean isCloseOnCompletion() throws SQLException { return original.isCloseOnCompletion(); }
  @Override public <T> T unwrap(Class<T> iface) throws SQLException { return original.unwrap(iface); }
  @Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return original.isWrapperFor(iface); }
}